version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/node.Dockerfile
    ports:
      - "3000:3000"
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s docker-entrypoint.sh
    working_dir: /src/usr/app
    environment:
      PORT: 3000
      DB_NAME: docker
      DB_PASSWORD: docker
      DB_HOST: mysql
      DB_USER: root
    command: npm run start
    volumes:
      - ./:/src/usr/app
    tty: true
    networks:
      - internal-network
    depends_on:
      - mysql

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal-network
    depends_on:
      - app


  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    ports:
    - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: docker
      MYSQL_ROOT_PASSWORD: docker
    networks:
      - internal-network


networks:
  internal-network:
    driver: bridge
