version: "3.7"
services:
  app:
    build:
      context: ./node
      dockerfile: ./node.Dockerfile
    ports:
      - "3000:3000"
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 30s node index.js
    environment:
      PORT: 3000
      DB_NAME: docker
      DB_PASSWORD: docker
      DB_HOST: mysql
      DB_USER: root
    volumes:
      - ./:/src/usr/app
      - /src/usr/app/node_modules
    tty: true
    networks:
      - internal-network
    depends_on:
      - mysql

  nginx:
    build:
      context: ./nginx
      dockerfile: ./nginx.Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal-network
    depends_on:
      - app


  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    restart: always
    tty: true
    ports:
    - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: docker
      MYSQL_ROOT_PASSWORD: docker
    networks:
      - internal-network


networks:
  internal-network:
    driver: bridge
